### ISSUE TITLE
RenderScript.h not found

### ISSUE THREAD

**Issue by Yair0007** [uelordi01/Call_RenderScript_from_NDK#2]
Thanks for a great project.
How do I get RS headers, and libs ?

**Comment by uelordi01** [comment]
Hi @Yair0007 : 
My apologies for my delayed response :( .
I have been very busy in these months.

The Renderscript headers and libs are located in the NDK, but in fact, you shouldn't really care about where are these libs located it depends on the NDK API that you are using. 

So this code on app/gradle, should be able to find the libraries in your SDK/NDK. 

```
       renderscriptTargetApi 19
        renderscriptSupportModeEnabled true
        renderscriptNdkModeEnabled true
```

Anyway I will execute the project again, and I will try to give you a better answer.

**Comment by uelordi01** [comment]
After some searching I found the libraries in the NDK folder

The libraries are located on: 

> YOUR_NDK/toolchains/renderscript/prebuilt/linux-x86_64/platform/arm64

![image_libs](https://user-images.githubusercontent.com/12067904/32044524-181648f2-ba3e-11e7-8d69-d78c267b1f08.png)

And the headers are located on: 

> YOUR_NDK/toolchains/renderscript/prebuilt/linux-x86_64/platform/rs/cpp

![headers_renderscript](https://user-images.githubusercontent.com/12067904/32044535-1becfa8e-ba3e-11e7-8e0b-3cfb8a792b80.png)
